dist: trusty
language: node_js
sudo: required
git:
  submodules: false
node_js:
  - '11.10'
before_cache:
  - nix-collect-garbage -d
cache:
  directories:
    - node_modules
    - nix
  timeout: 9000
before_install:
  - . gov-testchain/install-dapptools.sh
  - npm i -g yarn@latest
install:
  - yarn install
  - yarn build
script:
  - yarn testnet --ci yarn test
